import MovieCard from "./components/MovieCard.jsx";
import "./App.css"

const App = () => {

    return (
        <>  
            <MovieCard title="The Shawshank Redemption" image="https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSf1DK32xKMQzqSl8wnY1BLVu_gdwsRYzVSNM6A03r6c-fEwrif8raKzkFRuerw1KHdDICvOw" description=" A gripping tale of hope, friendship, and redemption behind bars" fullDec="Based on Stephen King’s novella and directed by Frank Darabont, this film follows Andy Dufresne (Tim Robbins), sentenced to life for a crime he didn’t commit, and his bond with fellow inmate Ellis “Red” Redding (Morgan Freeman). It’s a powerful meditation on the resilience of the human spirit and the enduring power of hope. Widely acclaimed, it has remained at the top of IMDb’s list since 2008" />
            <MovieCard title="The Godfather" image="https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" description=" A cinematic landmark chronicling the rise and cost of power in a Mafia dynasty." fullDec=" Francis Ford Coppola’s adaptation of Mario Puzo’s novel is an epic crime saga about the Corleone family, led by patriarch Vito (Marlon Brando) and his reluctant heir, Michael (Al Pacino). Lauded for its direction, screenplay, and performances, The Godfather is often hailed as one of the greatest films ever made." />
            <MovieCard title="A Space Odyssey" image="https://resizing.flixster.com/NbcqvUYbmW2Z4UI6aKjeJ6L8V-U=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/NowShowing/43074/43074_aa.jpg" description="A visionary sci‑fi masterpiece exploring humanity’s evolution and destiny." fullDec="Stanley Kubrick’s visually stunning journey—from prehistoric apes to the depths of space—delivers an ambitious exploration of intelligence, existence, and the unknown. Its pioneering cinematography, enigmatic narrative, and philosophical depth have cemented it as one of the most influential and debated films ever." />
            <MovieCard title="Casablanca" image="https://resizing.flixster.com/ai2GNkpxdxnU4pSv4NVjX5mL3O8=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p651_p_v8_az.jpg" description=" A timeless romantic drama set against the backdrop of WWII intrigue." fullDec=" Starring Humphrey Bogart and Ingrid Bergman, this classic unfolds in war‑torn Morocco. Bogart’s cynical Rick is reunited with his former love, Ilsa, leading to a poignant tale of sacrifice and moral choice. Casablanca continues to resonate with quotable lines, rich characters, and world-weary charm, earning its unshakeable legacy." />
            <MovieCard title="The Empire Strikes Back" image="https://m.media-amazon.com/images/I/71j4eFd2kpL._UF894,1000_QL80_.jpg" description="The darker, deeper sequel that reshaped the Star Wars saga." fullDec="Directed by Irvin Kershner, this film raises the stakes: Luke confronts personal doubt, Han and Leia’s romance deepens, and Darth Vader delivers an unforgettable twist. Its tone, character arcs, and score make it a benchmark in franchise storytelling."  />
            <MovieCard title="Citizen Kane" image="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Citizen_Kane_poster%2C_1941_%28Style_B%2C_unrestored%29.jpg/960px-Citizen_Kane_poster%2C_1941_%28Style_B%2C_unrestored%29.jpg" description=" Orson Welles’s groundbreaking debut exploring power, memory, and legacy." fullDec="Often called the greatest film ever made, this story of newspaper mogul Charles Foster Kane is notable for its innovative cinematography, narrative structure, and depth. Its influence on the art of filmmaking is immeasurable." />
            <MovieCard title="The Dark Knight" image="https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg" description="A superhero film elevated by moral complexity and an iconic villain." fullDec=" Christopher Nolan’s gritty, emotionally charged dive into Gotham’s descent into chaos features Heath Ledger’s haunting portrayal of the Joker and Christian Bale’s conflicted Batman. Its serious tone, thematic resonance, and thrilling set-pieces disrupted genre expectations."  />
            <MovieCard title="Pulp Fiction" image="https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg" description="Tarantino’s genre‑blending, dialogue‑driven mosaic of crime and pop culture." fullDe=" Interweaving gritty violence, dark comedy, and memorable characters—each segment reverberates with Tarantino’s sharp writing and playful structure. It’s a defining moment in ’90s cinema, influencing narrative style and indie filmmaking." />
            <MovieCard title="Schindler’s List" image="https://m.media-amazon.com/images/M/MV5BNjM1ZDQxYWUtMzQyZS00MTE1LWJmZGYtNGUyNTdlYjM3ZmVmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg" description=" A haunting and humanizing depiction of the Holocaust." fullDe="Steven Spielberg’s black-and-white epic portrays Oskar Schindler (Liam Neeson), an industrialist who transforms from profiteer to savior by protecting over 1,000 Jews from Nazi persecution. Its emotional power, historical significance, and aesthetic choice make it a vital work of art."  />
            <MovieCard title="Parasite" image="https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_.jpg" description=" A darkly comedic thriller illuminating class divides in South Korea." fullDe="Bong Joon-ho’s Oscar-winning masterpiece blends satire, suspense, and social commentary as a poor family infiltrates a wealthy household. Its storytelling, genre shifts, and cultural resonance earned it global acclaim and the Palme d’Or."  />
        </>
    );


}

export default App
